name: Build / Test on Linux

on:
  workflow_call:
    inputs:
      job-name:
        description: "Name for the job, which is displayed in the GitHub UI"
        default: "linux-job"
        type: string
      runner:
        description: 'Runner type to utilize'
        default: "linux.2xlarge"
        type: string
      docker-image:
        description: Identifies the Docker image by name.
        default: "ubuntu:latest"
        type: string

jobs:
  job:
    name: ${{ inputs.job-name }}
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a command inside the Docker container
        run: echo "Hello from the container!"

      - name: Check workplace
        run: |
          uname -a
          ls -lha
          pwd
          whoami
